<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "slavlee_gdpr_youtube"
 *
 * Auto generated by Extension Builder 2018-06-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Slavlee GDPR YouTube',
    'description' => 'Slavlee GDPR YouTube replaces all occurances of YouTube Embeddings with a notification notice to comply for the latest GDPR law.',
    'category' => 'plugin',
    'author' => 'Kevin Chileong Lee',
    'author_email' => 'info@slavlee.de',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.2.6',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
        	'php' => '7.0.0 - 7.2.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
